### ISSUE TITLE
Feature request: LDAP group mapping in resolver?

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#710] opened 2017-05-24 21:41 UTC
Currently the only way to set up a policy like _helpdesk_ while using LDAP resolver and Group membership is:
1 -  To use a search filter in the resolver definition
2 - Have support for `memberOf` in LDAP (which is NOT the default)
3 - Create a second realm (`newrealm`) and map it to 1
4 - Define a policy and bind it to realm created in 2

[Modern applications](https://docs.gitlab.com/ee/articles/how_to_configure_ldap_gitlab_ee/#group-sync) have moved away from this and are able to deal with standard group membership (in a ldap,  application-reserver group path). 
The reason is simple: in the pi case the user `user1` must explicitly use `user1@newrealm` in order for the new authorization (`helpdesk`) to come up. 

# Scenario

- privacyidea has its own bind dn and looks up users from a specific `Base DN`
- privacyidea has its own application group created in LDAP

```
ou=pi,ou=applications,ou=acme,ou=com
    |
    - cn=admin
    - cn=groupX
    - cn=groupY
    - cn=groupZ
```

# Design proposal

* Resolver
In the Resolver configuration, add a new form field called: "Group mapping DN" (or something), which would have the *optional* value of `ou=pi,ou=applications,ou=acme,ou=com` in this scenario.

* Policy
When `User-Resolver` is selected in a policy, if there is a `Group mapping DN` defined for the resolver, a (searchable?) drop-down would appear to pick a group: `admin`, `groupX`, `groupY`, `groupZ`.

# Behaviour proposal

The group membership follows the `AND` logic for policy matching: if all current existing logic matches AND the user is member of the group, then policy matches.

# Use-Case 

Dynamically being able to define e.g. a group of people who can "have" the `helpdesk` admin policy without having to define a new realm AND without having to support extended ldap attributes (like `memberOf`) AND having to define a new admin realm in the file (and server restart etc). Extras: no need to ever deal with "Admin-realm" option in the policy

**Comment by cornelinux** [comment] 2017-05-25 08:14
Modern applications do not only rely on LDAP but can find users in many different kind of user sources. This is why we chosen a generic approach - which was intentional by design.
In our design you can have the same effect in every type of user store. 
Your design request would be limited to LDAP.

In addition this is  major design change, which would effect the complete user resolvers and the complete policy handling. The policy handling is fine so far and avoids spaghetti code. 
This would be a challenging task to add such a functionality. And in my opinion this is not pressingly necessary - since you can have the desired functionality and it works well for all customers.

But you are welcome to contact NetKnights which may help you with this requirement on a paid basis.

**Comment by cornelinux** [comment] 2017-08-31 11:42
One other thing:
Your design would not allow a user to either act as adminsitrator or as normal user.

This way a user can 
login as ``splashx@helpdesk`` and get administrative tasks or as ``splashx`` and have normal user rights.

Closing this for now.

**Closed by cornelinux** 2017-08-31 11:42 UTC
Labels: buy this feature, feature request
