### ISSUE TITLE
LIST API can not retrieve all users

### ISSUE THREAD

**Issue by alexgv14** [privacyidea/privacyidea#2404] opened 2020-09-23 18:51 UTC
Calling the GET /users API limits the amount of users shown in the API to 100.

https://privacyidea.readthedocs.io/en/latest/modules/api/user.html

There is no way to increase that limit or page through them currently. I have no way to retrieve all of the users.

**Comment by cornelinux** [comment] 2020-09-23 20:35
This is by design, since you do not want to list all users. *search*! for the users.

You can also step through the list of users.
Fetching *all* users would overload the system.

Will close this shortly.

**Comment by alexgv14** [comment] 2020-09-23 20:41
@cornelinux i can understand that but there is also no pagination so you can not even step through the users say 10 at a time.

**Comment by cornelinux** [comment] 2020-09-23 20:48
Ah, yes, you are right.
No, there is not.

You can configure the user limit in resolvers, if you *really* need to query *all* users at once.

**Comment by alexgv14** [comment] 2020-09-23 20:51
@cornelinux how do you do that. I tried to change SIZELIMIT and nothing changed

**Comment by cornelinux** [comment] 2020-09-23 20:52
need input.

**Comment by alexgv14** [comment] 2020-09-23 20:55
In the resolverconfig table I added SIZELIMIT entry with value 500 and type int for that resolver which is a sqlreslover @cornelinux

**Comment by cornelinux** [comment] 2020-09-23 21:01
? I dont understand this. What did you do? "Type  int"?

**Comment by cornelinux** [comment] 2020-09-23 21:02
Closing this, since this is of no interest to anyone else. This is probably a misunderstanding and misconfiguration.
https://community.privacyidea.org is for misunderstandings.
@alexgv14 You are welcome to try to provide more details.

**Closed by cornelinux** 2020-09-23 21:01 UTC
Labels: Type: Question

**Comment by alexgv14** [comment] 2020-09-23 21:05
@cornelinux can you explain how you configured the user limits? I have tried to configure it. There is no documentation around that.

**Comment by cornelinux** [comment] 2020-09-23 21:15
No. Github is not the place for this.And you first have to provide more information what you have done.You need to type more. Last post.

**Comment by alexgv14** [comment] 2020-09-23 21:54
@cornelinux There is a table called `resolverconfig` where I have configured my resolver information. It holds information like the following:

<img width="319" alt="Screen Shot 2020-09-23 at 5 48 39 PM" src="https://user-images.githubusercontent.com/354629/94073291-3c48a580-fdc5-11ea-8a07-230571613535.png">

I am using a sqlresolver which I do not know if that has an impact on anything. 

I tried to configure the `SIZELIMIT` to 500 but that did not change the amount of users being returned on that API call. So, there are two options here. There is a bug in the code or I have something misconfigured. Since I can't find any information on how this is configured. I think there may be a bug. I am kindly asking that you could point me in the right direction as I have also posted in the community forum but no one knows the answer there either.

**Comment by cornelinux** [comment] 2020-09-24 04:54
Look at this! After 3 (**three**) hours you provided some minor hints, what you might have done.
Your first comment totally sucked and indicated that you are a lazy person. Noone can help you, if you do not provide enough information. It is **your responsibility** to provide this information in the first place. What have you done? Which guide did you follow? What and where and how have you configured? What did happen?
I guess you are in IT not only since yesterday, so you might already know, that more information help better so solve a problem quicker. In this light you might understand that you first comment is totally annoying.

We give the world great software. This does not mean that we are giving the world our time senselessly.

So rethink all your information, gather as much information as possible, which you think or know is relevant and state your question (since it is a wrong using of privacyIDEA) at https://community.privacyidea.org.
I think I said this earlier. And if you ignore this, I will in turn ignore you till the end of your life.

**Comment by alexgv14** [comment] 2020-09-24 13:39
hey @cornelinux I was able to fix the issue by combing through the source code. One there is indeed a bug. In the sqlresolver the configuration value that must be set is LIMIT and it can be set whatever you want. The bug is you can not just update those values you have to delete the sqlresolver and recreate it with the new values. 

```
{ 
        type: "sqlresolver", 
        Database: database,
        Driver: "mysql",
        Server: host,
        Port: "3306",
        User: user,
        Password: pass,
        Table: table,
        Limit: 500,
        Map: { 
          "userid": "userid", 
          "username": "email",
          "givenname": "givenname",
          "surname": "surname",
          "email": "email", 
          "password": "password" ,
        }
      }
```

I think you should be a little nicer to people who are using your software and trying to make it better / easier to understand.

**Comment by cornelinux** [comment] 2020-09-24 14:38
I understand your point of view.

But: We are not the IT guys. We are not here to take everybody at his hand and lead through everything.
When we ask a question, we expect an answer.
When we get an issue or a question, we expect that the requester already has put some effert into it and that the requester makes *our* life easier.

The requester can not only expect from us, that we make *his* life easier.

If you take something free of charge, you still need to put some effort into it. Maybe you will understand this.
