### ISSUE TITLE
First login with a WebAuthn token will fail

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#2116] opened 2020-03-19 18:44 UTC

**Comment by NuvandaPV** [comment] 2020-03-19 18:58
@plettich Can you still reproduce this with the current master? I swear I saw this as well, but it seems no matter what I do, I can't get this  to happen right now.

**Comment by plettich** [comment] 2020-03-27 18:33
@NuvandaPV Could not reproduce this either on a fresh privacyIDEA with the current master so i think we can close this.

**Closed** 2020-03-30 09:05 UTC
Labels: Prio: High, Topic: Token, Type: Possible bug
