### ISSUE TITLE
Add user attributes to policy conditions

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1645] opened 2019-05-23 19:06 UTC
Policies should not only match for *realms*, *resolvers* and *usernames* but also for arbitrary user attributes.

This way attributes can be dynamically read from the user source (like attributes from LDAP, group memberships...) and be used for matching policies.

**Comment by cornelinux** [comment] 2019-05-23 19:08
oups, this was already defined in #1436

**Comment by cornelinux** [comment] 2019-06-08 21:56
* We already pass the user information (user object) to the policy handling in [get_policies](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L464) and [get_action_values](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L638)
This is why we do not need to pass anything in addtion. The policy handling can determine the user object and determine it's attributes.

* [ ] We need to add a database field or whatever for the user_attributes. As the policy might match for several different user attributes at the same time, we need to be able to attach several attributes. to a policy. (Obviously we need a condition table).

**Comment by fredreichbier** [comment] 2019-06-12 09:18
Closing this because it's a duplicate of #1436.

**Closed by fredreichbier** 2019-06-12 09:18 UTC
Labels: Prio:High, Topic:Policy, feature request, main feature
