### ISSUE TITLE
Fix otpauth uri/qr code concerning hash algorithms

### ISSUE THREAD

**Issue by mjbecker** [privacyidea/privacyidea#1088] opened 2018-06-05 17:45 UTC
The generation of goo_url in hotptoken.py via cr_google is made with paramter
`hash_algo=params.get("hashlib", "sha1")`, which always seems to return, thus defaulting to hash algorith sha1.

If the default hash algorithm in the HOTP token settings is change from sha1 to sha256 or sha512 the otpauth uri / qrcode doesn't include the algorithm parameter, which results in incorrect initalisation of the otp client.

By substituting the above with `hash_algo=self.get_tokeninfo("hashlib","sha1"),` this seems fixed.

**Comment by cornelinux** [comment] 2018-06-05 20:18
Thanks for looking into this. I can not reproduce this. In my case the correct hashlib is contained in the ``params`` and in the token object (tokeninfo), since the hashlib was written to the tokeninfo in the ``update`` method here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/hotptoken.py#L323

I would like to understand how you problem occurs - so we also might add a corresponding test.
I also never saw this problem in the field.

I juest checked (I think) all possibilities and can not see this behaviour. Maybe also since I am checking on the current master branch.
Can you please explain, in which situation you get this result?

**Comment by mjbecker** [comment] 2018-06-05 21:46
I did a pip install following the instructions in the guide, version running is 2.22.2.
Realm: defrealm
Resolver: deflocal / Type passwdresolver  --> File /opt/privacyidea/etc/pi_passwd
The file was created with privacyidea-create-pwidresolver-user -u dvz -i 1000 >> pi_passwd

Only PI_LOGLEVEL = 10 is set in custom pi.cfg, all other values are defaults.

Starting the server with pi-manage runserver,
Logging in with user admin, going to config/tokens/hotp
Changing Default hash algorithm to sha256, Saving.
Logging out

Logging in with user from flat file pi_passwd
Navigating to token/enroll//
Selecting HOTP
Description: %
Pin: 123456

Clicking <Enroll Token”

Link created and qr code generated do not contain algorithm parameter.

otpauth://hotp/OATH00006AF0?secret=BDQYV3PGUWUYMLSKJXNUPIW2ZZLHTATQS6AAMENKFSX56HDZJ4IA&counter=1&digits=6&issuer=privacyIDEA

Using the link or the qr code to initialize the hotp in freeotp client, lets it generate OTP values with hash algorithm sha1 instead sha256, thus OTP values never match, so “authentication” fails.
After identifying this problem (at least in my installation) I changed the code  in hotptoke.py as mentioned in the PR and issued a python -m compileall hotptoken.py

Stopping/Starting the server again

Enrolling HOTP token as described above, but now the link generated is fine, as it contains the algorithm parameter
otpauth://hotp/OATH00030CC9?secret=5JFZTCRWCX3SR2XLYX7R5JVYKJAZ7F4OTWZNRYFK6VCJJ4OICYKA&counter=1&algorithm=sha256&digits=6&issuer=privacyIDEA

Importing into FreeOTP, OTP values match.



Von: Cornelius Kölbel [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Juni 2018 22:19
An: privacyidea/privacyidea
Cc: Becker, Michael; Author
Betreff: Re: [privacyidea/privacyidea] Fix otpauth uri/qr code concerning hash algorithms (#1088),


Thanks for looking into this. I can not reproduce this. In my case the correct hashlib is contained in the params and in the token object (tokeninfo), since the hashlib was written to the tokeninfo in the update method here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/hotptoken.py#L323

I would like to understand how you problem occurs - so we also might add a corresponding test.
I also never saw this problem in the field.

I juest checked (I think) all possibilities and can not see this behaviour. Maybe also since I am checking on the current master branch.
Can you please explain, in which situation you get this result?

**Comment by cornelinux** [comment] 2018-06-06 08:30
Thank you - I see.
This looks like the problem, that in case of *sqlite* or *runserver* some configuration settings are not active right away. I think configuration settings are cached and thus can lead to using old values. But in this case, your fix would not change anything. Since ``self.get_tokeninfo("hashlib")`` would also contain the old value.

In productive environmet we do not recommend using ``sqlite`` nor ``runserver``.

**Comment by mjbecker** [comment] 2018-06-06 10:47
Well, as least my testing shows, that it fixes the problem. I think even running with sqlite and runserver it should produce the correct uri. Maybe this a caching, timing or ORM related issue, but why shouldn’t it happen on apache with mysql?

**Comment by cornelinux** [comment] 2018-06-06 11:39
Well, you see - this is strange: The PR shouldn't fix the problem. So the real problem is somewhere else.
We will investigate this - this is why I do not close this issue. But the PR does not look like the right solution to me. I will also leave the PR open, till it is clear, what causes this issue.

**Comment by mjbecker** [comment] 2018-06-06 11:45
Probably you are right that the root cause is not found and the „fix“ shouldn’t work. I have already added some debug statements to see in which order the functions update and get_init_detail are called in the enrollment process.

**Comment by cornelinux** [comment] 2018-06-06 13:30
It took me a while of digging but finally I found the reason for this.
The user fetches the system config, when enrolling the token. The system config in most cases is ment for the administrator, so users usually are not allowed to read values from the system config...
...unless, the ``type`` of the config entry is "public".

The ``hotp.hashlib`` is not stored as public value. Thus the user within the UI will not fetch this information from the server. never.
So it seems like the hotp token class is missing a function like this:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/totptoken.py#L620

~~~~python
    @staticmethod
    def get_setting_type(key):
        settings = {"hotp.hashlib": "public"}
        return settings.get(key, "")
~~~~

**Comment by mjbecker** [comment] 2018-06-06 13:54
What I have observed, the 'hashlib' value is not present in the param dict when calling init (api/token.py). After returning succesfully with a tokenobject get_init_detail is already called with the same param dict, thus it still does not contain a value for 'hashlib'.

`[2018-06-06 14:21:23,519][22158][140638228928256][DEBUG][privacyidea.lib.tokens.hotptoken:322] UPDATE: Hashlib: sha256
[2018-06-06 14:21:23,519][22158][140638228928256][DEBUG][privacyidea.lib.tokenclass:497] TOKENCLASS_UPDATE sha256
[2018-06-06 14:21:23,565][22158][140638228928256][DEBUG][privacyidea.api.token:252] INIT None
[2018-06-06 14:21:23,603][22158][140638228928256][DEBUG][privacyidea.lib.tokens.hotptoken:221] CR_GOOGLE params.get: None
[2018-06-06 14:21:23,604][22158][140638228928256][DEBUG][privacyidea.lib.tokens.hotptoken:222] CR_GOOGLE get_tokeninfo: sha256`

The 'hashlib' value in upd_param dict in def update of hotptoken.py is handed over to TokenClass.update(self, upd_param, reset_failcount). But there is not used as the follwing code will not match key hashlib, it would only match key hotp.hashlib.

`for p in param.keys():
            if p.startswith(self.type + "."):
            self.add_tokeninfo(p, getParam(param, p))
`

It get's defintely set in def update of hotptoken.py

`self.add_tokeninfo("hashlib", hashlibStr)`

That is the reason why the fix works.

I have no overview of the complete code of course, but I'm not sure if the proposed method will fix the problem, as I still do not see how the value will get in the params dict before get_init_detail is called.

**Comment by cornelinux** [comment] 2018-06-06 14:30
> I have no overview of the complete code of course, but I'm not sure if the proposed method will fix the problem, as I still do not see how the value will get in the params dict before get_init_detail is called.

Via the API call.

**Comment by mjbecker** [comment] 2018-06-06 14:41
I see, it is done with the decorator function @prepolicy(init_token_defaults, request)

**Closed** 2018-06-07 08:28 UTC
