### ISSUE TITLE
Fix OTP LDAP_START TLS inconsistency

### ISSUE THREAD

**Issue by darrenche** [privacyidea/privacyidea#2025] opened 2020-02-12 22:46 UTC
#1806 # Top-level intent

What did you try to achieve?

Improve `Start_TLS` inside https://github.com/privacyidea/privacyidea/blob/db22f533badbff33ff112ae3ed546b59150c7272/privacyidea/lib/resolvers/LDAPIdResolver.py#L1011
### Steps to reproduce

1. When calling this function `testconnection()`

### Expected outcome

What do you think, how the system should have worked?

Should check the typing similar to how the following does uses the `is_true` wrapper:

Declaration:
https://github.com/privacyidea/privacyidea/blob/db22f533badbff33ff112ae3ed546b59150c7272/privacyidea/lib/resolvers/LDAPIdResolver.py#L345
Wrapper `is_true` used:
https://github.com/privacyidea/privacyidea/blob/db22f533badbff33ff112ae3ed546b59150c7272/privacyidea/lib/resolvers/LDAPIdResolver.py#L760

### Actual outcome

What did actually happen?

Causes a minor bug because the type was not checked and typed to boolean, depending on the parameters used.

### Configuration

* **privacyIDEA version**: 2.23
* **Installation method**: (from Ubuntu packages, github, PyPI, ...):  
* **Python version**: 2.7
* **Operating system**: Amazon Linux
* **Webserver**:
* **Token database**: (MySQL, PostgreSQL, ...): PostgreSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by darrenche** [comment] 2020-02-12 22:47
CC: https://github.com/privacyidea/privacyidea/pull/2021

**Comment by cornelinux** [comment] 2020-02-13 20:23
Please describe the problem you are experiencing with parameters to reproduce.
We do not see the problem.

**Comment by cornelinux** [comment] 2020-02-13 20:25
Why are you referencing #1806? It has nothing to do with your words. I am tempted to close this issue!!

**Comment by cornelinux** [comment] 2020-02-13 20:26
Oh wait. I am closing this issue.
You are actually saying: "Change the code this way".
Why? "Because it can cause *a* minor bug"

As soon as you are capable of opening decent issues, I will not close them!

**Closed by cornelinux** 2020-02-13 20:26 UTC
