### ISSUE TITLE
Creating tokens with Umlaut in Username not possible

### ISSUE THREAD

**Issue by mimugmail** [privacyidea/privacyidea#738] opened 2017-06-28 15:22 UTC
When there's a german umlaut in the username the enrollment of a token isn't possible.
The error is:
'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)

Username here was "Müller"

I know this is quite unusual but my customer has one .. 

Version tested was 2.19.

EDIT: Usersource is LDAP with simple bind

**Comment by ranomier** [comment] 2017-07-03 17:32
I have no idea about privacyidea.

But Linux only accepts ASCII as username.
Maybe its inherited. :)

**Comment by mimugmail** [comment] 2017-07-03 17:40
Yep, but the username is retrieved via LDAP/AD

**Comment by cornelinux** [comment] 2017-07-04 09:10
@mimugmail Can you please give more details about the LDAP? Is it AD or OpenLDAP? What system/distribution is the LDAP running on? What encoding is used?

**Comment by mimugmail** [comment] 2017-07-04 09:37
Sure! 
LDAP is running against W2K13 Server. This is my setup:
![image](https://user-images.githubusercontent.com/20438689/27824448-cfddf552-60ac-11e7-8e7a-a607e5f0965f.png)

Userfilter:
![image](https://user-images.githubusercontent.com/20438689/27824502-01c2b90e-60ad-11e7-8324-5493ac832e1e.png)


User found:
![image](https://user-images.githubusercontent.com/20438689/27824555-262f7944-60ad-11e7-843a-b6e64b7dde42.png)

The PI system itself is latest 2.19 via PIP / virtualenv on Debian 8

**Comment by cornelinux** [comment] 2017-07-17 13:48
**todo**: install 2K13 on bors

**Comment by mimugmail** [comment] 2017-07-17 13:59
@cornelinux Sorry it's 2012 of course. The customer has also a second DC 2008R2 with the same result

**Comment by cornelinux** [comment] 2017-07-17 14:25
of course! 2013 ;-)

**Comment by cornelinux** [comment] 2017-07-18 05:47
@mimugmail It just came to my mind, that this might not be due to ldap! Obviously the loginname resolves correctly as you screenshot shows.
If this occurs during token enrollment this could be everything:
* faulty formated log entry
* problem with the QR code...

Are you enrolling a smartphon token?

Can you please reproduce and provide the interesting part of the log file?

If you want to, you can upload the log file here: https://lancelot.netknights.it/owncloud/s/3SF2FO5Z19x98S8

**Comment by mimugmail** [comment] 2017-07-18 07:27
@cornelinux It happens when I click on the username, so it's before enrolling. 
Sent to you a full debug log, hope that's ok.

**Comment by cornelinux** [comment] 2017-07-18 16:15
OK, I am just reproducing it. You are in the *user list* and then selecting the user "Müller"

Then you get the error. It comes from fetching tokens for the user "Müller". This call:

    GET https://localhost/pi//token/?page=1&pagesize=5&realm=mimi&user=m%C3%BCller


Unfortunately when in the ``token->enroll`` view and searching for the user

    POST https://localhost/pi//token/init

will also fail for the user "Müller".

**Comment by cornelinux** [comment] 2017-07-18 16:18
@fredreichbier bummer. ``{n!s} ?``

**Comment by cornelinux** [comment] 2017-07-18 16:23
Plus we have a "{0!s}" in the log.debug in the cache wrapper.

**Comment by cornelinux** [comment] 2017-07-20 13:55
Add unittests for umlaut-users. Extend the ldap3mock ind commit a16271aaac4e2321c1b09b7801eab650df05324d.
The two 738-branches need to be merged.

**Closed** 2017-07-21 13:48 UTC
Labels: Topic:LDAP

**Comment by mimugmail** [comment] 2017-07-31 07:40
@cornelinux @fredreichbier Do you have any date when 2.20 will be released? My customer is waiting for this feature and I don't want to patch around in the live system :)

**Comment by cornelinux** [comment] 2017-07-31 09:06
Are you running Ubuntu or a pip install? We could try to do a 2.19.2

**Comment by mimugmail** [comment] 2017-07-31 09:13
This would be great! Its PIP virtual env on Debian 8. Thanks, Michael

Am 31.07.2017 11:06 vorm. schrieb "Cornelius Kölbel" <
notifications@github.com>:
