### ISSUE TITLE
delete a assigned tokengroup and the tokenlist can't be shown

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#3423] opened 2022-12-19 12:07 UTC
version: master
Create a tokengroup.
Create token and assign the tokengroup
delete the tokengroup 
the tokenlist is empty and a none valid json-response error raise

**Comment by plettich** [comment] 2023-01-05 11:32
I can not reproduce this, actually, i get an internal server error due to the fact that the database entry for the tokengroup has a foreign key constraint to the `tokentokengroup` table. So in fact it should only be able to be deleted, when no tokens are assigned to the tokengroup anymore. We should make sure to check the constraint like you can not delete a resolver when it is still part of a realm.

**Closed** 2023-02-07 15:05 UTC
Labels: Status: Waiting for merge into master, Type: Possible bug
