### ISSUE TITLE
column pidea_audit.info too short per default?

### ISSUE THREAD

**Issue by jmozd** [privacyidea/privacyidea#2440] opened 2020-10-08 20:00 UTC
using a push token with privacyidea 3.4 repeatedly led to error messages

> [ERROR][privacyidea.lib.auditmodules.sqlaudit:261] exception DataError('(pymysql.err.DataError) (1406, "Data too long for column \'info\' at row 1")',)
> [ERROR][privacyidea.lib.auditmodules.sqlaudit:262] DATA: {'success': True, 'serial': None, 'user': [], 'realm': ['customer.com'], 'resolver': '', 'token_type': None, 'client': '192.168.199.26', 'client_user_agent': 'chrome', 'privacyidea_server': > 'privacyidea.customer.com', 'action': 'POST /policy/<name>', 'action_detail': 'pushTokenAuthentication', 'info': "{'action': ['push_allow_polling=allow', 'push_ssl_verify=0', 'push_text_on_mobile=Confirm login to your account', 'push_title_on_mobile=Company 2FA', 'push_wait=60'], 'scope': 'authentication', 'realm': ['company.com'], 'resolver': '', 'user': [], 'active': True, 'check_all_resolvers': False, 'client': 'client.company.com', 'time': '', 'priority': 1, 'conditions': [], 'adminuser': [], 'pinodes': [], 'adminrealm': [], 'name': 'pushTokenAuthentication'}", 'administrator': 'theadmin', 'policies': ''}

Looking at the data that was being tried to insert, it's length was close to 500 characters, so I decided to "upgrade" from the installation-defined 50 characters to 2000, just in case ;)

> MariaDB [privacyidea]> alter table pidea_audit modify column info varchar(2000);

Any reason the info field was limited to 50 characters, maybe I missed some step while setting up?

**Comment by cornelinux** [comment] 2020-10-09 14:01
The reason is named "Oracle".

This is a duplicate of #1756, which is currently merged in the master branch. 
Thanks a lot.

**Closed by cornelinux** 2020-10-09 14:01 UTC

**Comment by jmozd** [comment] 2020-10-09 14:07
saw & read that one, but dismissed it as not applicable: Truncation of the entry (if column is set to just 50 chars) actually wasn't what I thought is wanted, but rather to have the full entry in the log :+1: 

But since you have this issue on your "radar" already, we can keep #2440 closed :+1:

**Comment by cornelinux** [comment] 2020-10-09 14:14
You are misunderstanding.
With the above mentioned merge you can set your info column to 2000 and have it still truncated at 2000.

Thank you, the *we* can keep this one closed.
