### ISSUE TITLE
Can't create resolvers, realms or SMTP servers on fresh install

### ISSUE THREAD

**Issue by psy-q** [privacyidea/privacyidea#2683] opened 2021-03-24 14:51 UTC
### Top-level intent

Creating a passwdresolver [as described in the documentation](https://privacyidea.readthedocs.io/en/v3.5.1/firststeps/realm.html#first-steps-realm)

### Steps to reproduce

1. Set up a fresh instance of privacyIDEA using virtualenv, pip3 on Debian 10, with MySQL as database, as per [the documentation](https://privacyidea.readthedocs.io/en/v3.5/installation/pip.html). The workaround described in #2629 was necessary to start the server. `PI_AUDIT_SQL_TRUNCATE = True` from #525 was necessary to prevent exceptions.
2. Create an admin user and log in to the web UI
3. Navigate to Config -> Users -> New passwdresolver
4. Fill in the field, use any name, point to /etc/passwd
5. Press "Save resolver"

### Expected outcome

A passwdresolver should have been created.

### Actual outcome

"500 Internal Server Error" pops up in the top right corner. See below for server logs.

The field that SQLAlchemy complains about does indeed not have a default value (its definition is `id int(11)` and it has the `PRIMARY KEY` attribute). Since there is no `auto_increment` and the query `INSERT INTO resolver (name, rtype) VALUES (%s, %s)` does not provide an id, the query cannot succeed because primary keys are not allowed to be NULL.

This is the table `resolver`:

```
MariaDB [privacyidea]> describe resolver;
+-------+--------------+------+-----+---------+-------+
| Field | Type         | Null | Key | Default | Extra |
+-------+--------------+------+-----+---------+-------+
| id    | int(11)      | NO   | PRI | NULL    |       |
| name  | varchar(255) | NO   | UNI | NULL    |       |
| rtype | varchar(255) | NO   |     | NULL    |       |
+-------+--------------+------+-----+---------+-------+
```

A similar problem appears with SMTP servers:

```
[SQL: INSERT INTO smtpserver (identifier, server, port, username, password, sender, tls, description, timeout, enqueue_job) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('My-SMTP', 'smtp.example.com', 25, '', 'FAILED TO ENCRYPT PASSWORD!', 'privacyidea@example.com', 0, '', 10, 0)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-03-25 10:06:09,123][21574][140304165570368][ERROR][privacyidea.lib.auditmodules.sqlaudit:306] exception IntegrityError('(MySQLdb._exceptions.IntegrityError) (1364, "Field \'id\' doesn\'t have a default va
lue")')
```

### Configuration

* **privacyIDEA version**: 3.5.1
* **Installation method**: PyPI
* **Python version**: 3.7.3
* **Operating system**: Debian GNU/Linux 10
* **Webserver**: None (test server/debug)
* **Token database**: MariaDB 10.3.27
 
### Log file

```
[2021-03-24 15:40:46,478][21574][140304165570368][ERROR][privacyidea.lib.auditmodules.sqlaudit:307] DATA: {'startdate': datetime.datetime(2021, 3, 24, 15, 40, 46, 452045), 'success': True, 'serial': None, 'user
': None, 'realm': None, 'resolver': None, 'token_type': None, 'client': '10.150.0.112', 'client_user_agent': 'firefox', 'privacyidea_server': 'privacyidea-test.pink.zhdk.ch:5000', 'action': 'GET /system/', 'act
ion_detail': '', 'info': None, 'administrator': 'admin', 'policies': ''}
[2021-03-24 15:41:54,917][21574][140304165570368][ERROR][privacyidea.app:1892] Exception on /resolver/passwresolver [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1364, "Field 'id' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/api/resolver.py", line 147, in set_resolver
    res = save_resolver(param)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/lib/resolver.py", line 126, in save_resolver
    resolver_id = resolver.save()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/models.py", line 124, in save
    save_config_timestamp()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/privacyidea/models.py", line 99, in save_config_timestamp
    c1 = Config.query.filter_by(Key=PRIVACYIDEA_TIMESTAMP).first()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3507, in __iter__
    self.session._autoflush()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1628, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1617, in _autoflush
    self.flush()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/privacyidea/venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb._exceptions.IntegrityError) (1364, "Field 'id' doesn't have a default value")
[SQL: INSERT INTO resolver (name, rtype) VALUES (%s, %s)]
[parameters: ('passwresolver', 'passwdresolver')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

[2021-03-24 15:41:54,938][21574][140304165570368][ERROR][privacyidea.lib.auditmodules.sqlaudit:306] exception IntegrityError('(MySQLdb._exceptions.IntegrityError) (1364, "Field \'id\' doesn\'t have a default value")')
[2021-03-24 15:41:54,938][21574][140304165570368][ERROR][privacyidea.lib.auditmodules.sqlaudit:307] DATA: {'startdate': datetime.datetime(2021, 3, 24, 15, 41, 54, 858301), 'success': False, 'serial': None, 'user': None, 'realm': None, 'resolver': 'passwresolver', 'token_type': None, 'client': '10.150.0.112', 'client_user_agent': 'firefox', 'privacyidea_server': 'privacyidea-test.pink.zhdk.ch:5000', 'action': 'POST /resolver/<resolver>', 'action_detail': '', 'info': '500 Internal Server Error: The server encountered ', 'administrator': 'admin', 'policies': ''}
```

**Comment by plettich** [comment] 2021-03-26 10:28
Hi @psy-q 
unfortunately i can not reproduce Your issue. Using the same steps i end up with the following table:
```
MariaDB [pi]> describe resolver;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | NO   | UNI | NULL    |                |
| rtype | varchar(255) | NO   |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
```
The auto-increment is created with the `Sequence` statement in the column definition here:
https://github.com/privacyidea/privacyidea/blob/947846a07f64caaa8847ce719a0b736b69cf2ae3/privacyidea/models.py#L985

Did You use `pi-manage createdb` to create/initialize the tables?

**Comment by psy-q** [comment] 2021-03-26 10:52
> Did You use `pi-manage createdb` to create/initialize the tables?

Yes, I used the commands as documented [here](https://privacyidea.readthedocs.io/en/v3.5/installation/pip.html#database). On Monday I can retry it on an empty database.

**Comment by psy-q** [comment] 2021-03-29 07:51
I deleted and recreated the database, ran the steps starting from `pi-manage createdb` again and now there is an auto_increment attribute. I don't understand why this didn't appear after the first run.

We've also managed to reproduce the problem on openSUSE and when using Sqlite, though. It doesn't happen on an older CentOS. I will gather more information on when and why it happens.

**Comment by brunocascio** [comment] 2021-03-31 15:19
I'm having the same issue in an already running privacyidea server

**Comment by brunocascio** [comment] 2021-04-02 21:52
The weird thing is droping and recreating the database, works. Does it seem something related to the sequence index, might be some migration file? I really don't know, but it's made me impossible to upgrade privacyidea in the future because I can't drop the database in production :/

**Comment by psy-q** [comment] 2021-04-03 07:51
I've tested the initial database setup several times now on Debian 10 and openSUSE Tumbleweed (the latter runs Python 3.8.8, MariaDB 10.5.9, Sqlite 3.35.2). I managed to reproduce it only one more time on Debian, and I see no real pattern for what's happening. But as Bruno is saying, dropping the database and recreating it can fix the issue.

**Comment by brunocascio** [comment] 2021-07-28 16:58
Any update? :(

**Comment by plettich** [comment] 2021-07-30 09:47
> Any update? :(

unfortunately not. I still can't reproduce this issue. I'll try with Your docker setup, maybe this sheds some light on it.
Can You create the missing sequence afterwards in Your production db?

**Comment by plettich** [comment] 2021-08-03 13:58
@brunocascio i tested with Debian 10 and mssql and still could not reproduce this.
But it looks like You are running the migration every time the container starts. Depending on the current version of the database this might lead to running some migration scripts all the time. While usually this should not do any harm it is possible that repeated failed migrations leave the db in an inconsistent state. 
The database migration should only be done once when the software is updated.

**Comment by brunocascio** [comment] 2021-08-05 13:18
> @brunocascio i tested with Debian 10 and mssql and still could not reproduce this.
> But it looks like You are running the migration every time the container starts. Depending on the current version of the database this might lead to running some migration scripts all the time. While usually this should not do any harm it is possible that repeated failed migrations leave the db in an inconsistent state.

Hi @plettich, yes, since we're using automatic deployment we need to ensure the database is also up-to-date. It shouldn't happen, but it's ok I'll remove that automatic part and run the migrations by hand.

Thanks!

**Comment by plettich** [comment] 2021-09-17 10:18
I'll close this for now. If there is any way to reliably reproduce this issue, we'll look into it again.

**Closed by plettich** 2021-09-17 10:18 UTC
