### ISSUE TITLE
User can not enroll email token and throws ERR905: Missing parameter: 'otpkey'

### ISSUE THREAD

**Issue by foot3print** [privacyidea/privacyidea#707] opened 2017-05-18 12:08 UTC
## Setup
privacyidea 2.18.1
ubuntu 16 xenial
apache2
mysql
userstore = LDAP
OTPPIN = userstore PW
realm = user_realm

## Policies
- users can only enroll following tokens: totp,sms,email
- users can NOT enroll OTPPIN or change OTPPIN

## What did you try to do?
- login as 'username', PW+Registrationkey -> success
- enroll EMAIL token - failed! ERR905: Missing parameter: 'otpkey' (red bubble)

## What outcome did you expect?
- EMAIL token of username will be enrolled.

## What outcome did you experience?
- ERR905: Missing parameter: 'otpkey' (red bubble)

##NOTE
- if i login using an admin account and enroll an EMAIL token it does not throw this error.
- using 'username' @ user_realm in enrolling other TOKENS such as TOTP, SMS ended successfully without this error.

## Log file
PI_LOGLEVEL = 10
- [2017-05-18 14:00:50,088][24986][140390785046272][INFO][privacyidea.lib.user:193] userid resolved to u'1acba47f-711b-4bfe-9325-c123746e3f59' 

- nothing follows... no relevant logs related to 'ERR905: Missing parameter: 'otpkey'

### Update
This only happens IF the user has NO TOKEN at all. AFTER enrolling other token first such as TOTP or SMS, I can enroll EMAIL token without errors again.
- I deleted AGAIN all of the user's token and tried to enroll EMAIL token first. There goes the ERROR again.
- I tried to enroll TOTP first then subsequently enroll EMAIL token. - NO errors.

**Comment by cornelinux** [comment] 2017-05-18 12:41
The REST call should contain a parameter "genkey"=True.
Can you please put your browser in developer mode and watch the network traffic?

I am not aware that we changed some things at this part. At least I can not reproduce it on the current development branch 2.19dev.

By the way: The current stable version is 2.18.1.

**Comment by foot3print** [comment] 2017-05-19 10:18
@cornelinux 
Thanks for the reply! Sorry, I forgot the ".1" but I am using 2.18.1. ;-) I placed the browser in developer mode and here are the traffic results:

After successfully logging in using userstorePW+registration token.
#NOTE disabled TOKENWIZARD
Case 1 - User has no tokens and will enroll email token first - Fail but still CREATED email token
Browser debug: POST init
   Params->
      timeStep: 30
      otplen: 6
      genkey: false
      type: "email"
      hashlib: "sha1"
      radius.system_settings: true
      email: "myemailadd@DOMAIN.com"
      totp.hashlib: "sha1"
      description: "first email token"
      user: "username"
      realm: "userrealm"
#TOKEN created is usable.

Case 2 - User created other tokens first then created email token - SUCCESS NO ERROR
Browser debug: POST init
   Params->
      timeStep: 30
      otplen: 6
      genkey: true
      type: "email"
      hashlib: "sha1"
      radius.system_settings: true
      email: "myemailadd@DOMAIN.com"
      totp.hashlib: "sha512"
      description: "email token after creating totp"
      user: "username"
      realm: "userrealm"

The TOTP token was previously created with sha512, timestep:30 and the box "Generate the OTP key on the server" is also checked. It appears that the default genkey is set to false which is why i got the ERR905 and it changed when i first enrolled the totp token and checked the box.

Regards,

**Comment by iamohtep** [comment] 2017-05-22 08:54
Hello,

maybe its related to the default token_type under the user policy. I did not set the default token_type before because the tokenwizard is also disabled/ not checked. After I selected the default token_type to 'email' the error did not appear anymore. So, i think that would be my workaround or maybe that is the way it should be if you have a similar Setup as mine. ;-)

You can close this Ticket if its the correct way or if further feedback/debug is not necessary. Thanks!


Regards,

**Comment by foot3print** [comment] 2017-05-22 09:01
Hello,

maybe its related to the default token_type under the user policy. I did not set the default token_type before because the tokenwizard is also disabled/ not checked. After I selected the default token_type to 'email' the error did not appear anymore. So, i think that would be my workaround or maybe that is the way it should be if you have a similar Setup as mine. ;-)

You can close this Ticket if its the correct way or if further feedback/debug is not necessary. Thanks!

Regards,

**Comment by cornelinux** [comment] 2017-05-22 09:27
Thanks for the investigation. We will look into this and see, if we need to take further actions.

**Comment by cornelinux** [comment] 2017-08-17 08:23
I can not reproduce this with 2.20dev.

1. User has initially a reg token and logs in with this reg token
2. User has no tokens
3. user enrolls an Email-Token, no problem.

I configured the policies for allowed tokentypes and set pin. ``genkey=true`` is contained in the POST parameters.

Which additional policy do you have in place?

Is it possible, that you check this behaviour with 2.19.1 or 2.20dev?

**Comment by foot3print** [comment] 2017-08-18 07:02
Hi !

hmmm Im running 2.19.1 with the same setup in Ubuntu Xenial but could not reproduce this error anymore. We opted not doing a 'user' based registration in which the 'admin' has to create a registration token.

`timeStep	30
otplen	6
genkey	true
type	"email"
hashlib	"sha1"
radius.system_settings	true
email	"ananda.joseph.baluyot@desy.de"
totp.hashlib	"sha1"
description	"test"
validity_period_start	""
validity_period_end	""
user	"pwbalu"
realm	"users"
`

I think this is already resolved. Thanks for investigating!

Cheers,

**Closed** 2017-08-18 07:04 UTC
