### ISSUE TITLE
User column too short in pidea_audit

### ISSUE THREAD

**Issue by cwmoller** [privacyidea/privacyidea#1922] opened 2019-11-12 09:45 UTC
### Top-level intent

We use UserPrincipalName for authentication, and usernames can easily be 30 characters long. The `pidea_audit` table only has space for 20 characters, and therefore doesn't log usernames.

### Steps to reproduce

1. Have usernames longer than 20 characters
2. View the tokens for a user with a username longer than 20 characters

### Expected outcome

User column in the audit log should be populated.

### Actual outcome

User column in the audit log is empty.

Increasing the size of the column (`alter table pidea_audit modify user varchar(64);`) leads to proper functioning.

### Configuration

* **privacyIDEA version**: 3.1.1
* **Installation method**: pip
* **Python version**: 2.7.15+
* **Operating system**: Ubuntu 18.04.3 LTS
* **Webserver**: nginx 1.16.1
* **Token database**: MariaDB 10.3.20

### Log file
```
[2019-11-12 08:35:46,605][18][140379093595968][ERROR][privacyidea.lib.auditmodules.sqlaudit:259] exception DataError('(pymysql.err.DataError) (1406, u"Data too long for column \'user\' at row 1")',)
[2019-11-12 08:35:46,605][18][140379093595968][ERROR][privacyidea.lib.auditmodules.sqlaudit:260] DATA: {'info': 'realm: None', 'administrator': u'sanitized.admin', 'realm': u'default', 'policies': '', 'success': True, 'privacyidea_server': 'sanitized.fqdn', 'client_user_agent': 'firefox', 'token_type': None, 'client': '2001:4860:4860:9000:20b2:2f59:8272:7e4c', 'user': u'sanitized@sanitized.com', 'resolver': u'sanitized.com', 'action_detail': '', 'action': 'GET /token/', 'serial': None}
```

**Comment by cornelinux** [comment] 2019-11-12 10:07
This is a duplicate of #1756 
It is intended and known. You could however lengthen the column yourself, but we can not enlarge the column in general due to other overall length limitations with other databases.

**Closed by cornelinux** 2019-11-12 10:07 UTC
