### ISSUE TITLE
API becomes completely inresponsive when LDAPS is unresponsive

### ISSUE THREAD

**Issue by karstennilsen** [privacyidea/privacyidea#505] opened 2016-10-05 06:49 UTC
When LDAPS of a resolver becomes unresponsive the whole API of PrivacyIDEA times out, sometimes you get a response after a **few minutes**:
`{"jsonrpc": "2.0", "signature": "21215705100525925526001178551476033771653498724391906956280249253111060822316509310175196477621450483516997732619871233723941621201689999074202038271716356677793498543584115065715229251630719925052266683709304253376472011668484302151989706737701716636173170080788630558218823726870273689020152521853454294098474158531364764427602660339069925754676955912011409504621486406497423933028177726028851185824974511242461855690737519369415490702041911845242305176774548042999305981429634394012844695996052325703719912616190558123728454896512909277189077877259740544201813640435575019857660167144089372231193637771111284089556", "detail": null, "version": "privacyIDEA 2.13", "result": {"status": false, "error": {"message": "(OperationalError) (2002, \"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\") None None", "code": -500}}, "time": 1475645426.145718, "id": 1}`

I tested MySQL, it was 100% working fine. After fixixng the LDAPS by recovering a domain controller everything worked fine.

Would be nice if the API still kept working so you could sign in on the webpanel and analyze what's going wrong :) Or if it would return a response showing it has troubles with LDAPS in stead of MySQL.

# Versions

privacyIDEA:
Installation method:
- [ ] Debian

OS: Debian 8.5 (package python-privacyidea)

Webserver: Apache 

LDAPS provider: Win 2008R2 Domain Controller

# Log file
The only thing usefull logged during the issue where a few entries of this (not on every request):
```[2016-10-05 07:30:00,505][704][140347890079488][ERROR][privacyidea.app:1423] Exception on /validate/check [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/validate.py", line 99, in before_request
    g.policy_object = PolicyClass()
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policy.py", line 309, in __init__
    policies = Policy.query.all()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2320, in all
    return list(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session
    **kw)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection
    close_with_result=close_with_result)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1798, in contextual_connect
    self.pool.connect(),
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 963, in _do_get
    return self._create_connection()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 538, in __connect
    connection = self.__pool._creator()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)") None None```

**Comment by cornelinux** [comment] 2016-10-05 20:53
Thanks for reporting this. 

First: You can set the timeout of the LDAP resolver and you can use more than one ldap server to do redundant LDAP resolving.

To reproduce and evaluate we need some more input:
* Which user tried to login to the WebUI? (Internal Admin?)
* Was this resolver in the default realm.
* Please specify "unresponsive". Would this be the same effect with the AD being down?
* Please provide more details on the resolver definition (cache, timeout, limit)...

**Comment by karstennilsen** [comment] 2016-10-05 21:32
The timeout is 5 seconds (like default), but the result was a timeout way worse.

- Login with internal admin failed. (the one set during setup of PrivacyIDEA)
(because of this you were unable to login to webpanel)
- This is the only resolver of the default realm indeed.
- Good question, our primary domain controller hung in a partly working state because of our back-up software. So probably there was some kind of LDAP response, but not what you would expect. Because we were first focusing on restoring services and rebooted I now can't really reproduce it. So probably analyze if the code also times out if it's getting unexpected LDAP data.
- This is a dump from resolver config:
```id;resolver_id;Key;Value;Type;Description
1;1;filename;/etc/passwd;;
2;2;BINDDN;CN=srv-privacyidea-otp,OU=ServiceAccounts,DC=ourdomain,DC=com;string;
3;2;AUTHTYPE;Simple;string;
4;2;LDAPFILTER;(&(sAMAccountName=%s)(objectClass=person));string;
5;2;LDAPBASE;DC=ourdomain,DC=com;string;
6;2;EDITABLE;0;bool;
7;2;LDAPURI;ldaps://dc1.ourdomain.com;string;
8;2;LDAPSEARCHFILTER;(sAMAccountName=*)(objectClass=person);string;
9;2;UIDTYPE;DN;string;
10;2;BINDPW;averylonghashwashere;password;
11;2;USERINFO;{ "username": "sAMAccountName", "phone" : "telephoneNumber", "mobile" : "mobile", "email" : "mail", "surname" : "sn", "givenname" : "givenName" };string;
12;2;TIMEOUT;5;int;
13;2;SCOPE;SUBTREE;string;
14;2;SIZELIMIT;5000;int;
15;2;NOREFERRALS;1;bool;
16;2;LOGINNAMEATTRIBUTE;sAMAccountName;string;
```

**Comment by cornelinux** [comment] 2016-10-05 21:45
There is nothing to fix here.
You could optimize your resolver configuration.

**Closed by cornelinux** 2016-10-05 21:45 UTC

**Comment by karstennilsen** [comment] 2016-10-05 22:08
So it's by ok that the whole API becomes unresponsive (response time more than a minute) as soon as an LDAP server doesn't reply properly? Strange :)

**Comment by cornelinux** [comment] 2016-10-06 15:02
The problem is, that there is no way for me to reproduce this and you can not reproduce this, either So there is nothing more than this vague observation. I never saw this in any installation. Plus: I very much assume, that it is *not* your AD but rather some network issue. More than a minute sounds more like the mysql database and not like this LDAP, because there is no LDAP request involved. (How would you test, that the mysql is fine)

And yes, **it is OK that the whole API becomes unresponsive**. As you are using open source software under the AGPLv3, which claims that the software "comes without any warranty". 
https://github.com/privacyidea/privacyidea/blob/master/LICENSE
So 
* either *you* fix this, 
* you provide enough information to have someone fix this,
* you get *warranty* by getting an enterprise edition,
* or you get and pay someone to investigate this really vague, non-reproducable issue.
But it will not work out in any open source project to report an unreproducable glimpse and then go bashing the software.

**Comment by karstennilsen** [comment] 2016-10-06 15:08
I know it comes with no warranty, I appreciate what you are doing! It was only a strange way to close the issue. 'No way to reproduce, so I'm closing the issue.' would have been more clear I guess. If the issue reoccurs I will try to get enough information to reproduce :)

**Comment by cornelinux** [comment] 2016-10-06 15:52
OK, thanks.
