### ISSUE TITLE
Support LDAP3 version 2.7.x

### ISSUE THREAD

**Issue by sluitz** [privacyidea/privacyidea#2176] opened 2020-04-28 19:55 UTC
Hello,

The ldap3 requirement in master was recently updated from 2.6.1 to 2.7. This breaks LDAP/AD (Samba4 AD) authentication on my test system (CentOS-7, Python 3.6, virtualenv). 

All authentications fail with the debug log below. Reverting ldap3 back to 2.6.1 makes authentication work again. 

This appears to be caused by https://github.com/cannatag/ldap3/issues/797 in ldap3, specifically this change: https://github.com/cannatag/ldap3/commit/266c3603fe3877760aea4180f7552ad1ea32dd0b

Disabling check_backslash() in ldap3/protocol/formatters/validators.py also makes PI work again.  

Best -- Steffen 
 

```
2020-04-28 13:24:42,184][27655][139826675607296][DEBUG][privacyidea.lib.user:379] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/user.py", line 367, in check_password
    if y.checkPass(uid, password):
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 327, in checkPass
    bind_user = self._getDN(uid)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 258, in cache_wrapper
    f_result = func(self, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 451, in _getDN
    search_userId = self._trim_user_id(userId)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 431, in _trim_user_id
    userId = trim_objectGUID(userId)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyIDEA-3.3-py3.6.egg/privacyidea/lib/resolvers/LDAPIdResolver.py", line 158, in trim_objectGUID
    userId = uuid.UUID(u"{{{0!s}}}".format(userId)).bytes_le
  File "/usr/lib64/python3.6/uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

```

**Comment by cornelinux** [comment] 2020-04-28 21:32
Thank you for pointing this out! 
Please use the tag v3.3.1dev1, which is the latest stable tag.

**Comment by cornelinux** [comment] 2020-06-17 08:59
We should check, if this can be fixed in ldap3

**Comment by cornelinux** [comment] 2020-06-18 12:24
On the master branch I stumpled upon a problem with ``Cannot pass user_object as well as user``.

The userobject had an empty ``loginname``, while the username was actually given.

Tracking this down, I saw, that this occurred, since the ldap resolver had 2 login attributes.
With two login attributes, we touch this code:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/user.py#L120

Then with ldap3 2.7 we fail in this line:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L507
and get an empty result. 
With ldap3 2.6.1 everything works fine!

So I strongly recommend to revert to ldap3 2.6.1, as long as there is no ldap3 2.7.1 available!

**Comment by cornelinux** [comment] 2020-06-18 12:25
What kind of buttons am I hitting blindly? I never meant to close this :-)

**Comment by plettich** [comment] 2020-06-24 10:13
I couldn't reproduce this. Reverting `ldap3` to 2.6.1 is no problem but we should keep this monitored.

**Comment by cornelinux** [comment] 2020-09-21 19:51
2.8.1 is out!

**Comment by plettich** [comment] 2020-10-05 13:33
Hi @sluitz 
do You still get that error with the current master (ldap3 pinned to 2.8.1)?

**Comment by cornelinux** [comment] 2020-11-01 13:02
I remove the label "high" since we already have 2.8.1 and wait for feedback.

**Comment by cornelinux** [comment] 2020-12-10 10:18
We will ship privacyIDEA 3.5 with ldap3 2.8, so I am closing this issue.

**Closed by cornelinux** 2020-12-10 10:18 UTC
Labels: Status: Waiting for feedback, Topic: LDAP
