### ISSUE TITLE
Idea: filter conditions for endpoints

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2289] opened 2020-07-08 10:27 UTC
Many support cases with event handlers are due to the fact that people configure event handlers with conditions but do not consider that certain parameters are just not contained in the request to be tested.

We could implement  a list of possible parameter for every endpoint and filter the conditions list accordingly in the WebUI.

There are two possibilities to setup this list:
- The list is generated dynamically (how?)
- The list is compiled manually (hardcoded) and updated whenever the endpoints are changed

related to #2148

**Comment by cornelinux** [comment] 2020-07-21 12:41
You are right. But this would be honestly a nearly impossible task.
Also: This would contain a lot of implicit logic. Imagine: Another event handler could actually **add** a parameter. Then our logic would tell, no this paramater/condition is not aplicable for this endpoint. Then the expected behaviour would break.

This was not done in the first place, because it is too complicated *and* it is to restrictive.

**Comment by cornelinux** [comment] 2020-11-16 08:50
I am closing this, since I do not see that we will do it within the next two years.

**Closed by cornelinux** 2020-11-16 08:50 UTC
Labels: Type: Idea!
