### ISSUE TITLE
pgsql | Connection does not get closed properly

### ISSUE THREAD

**Issue by mrmstn** [privacyidea/privacyidea#870] opened 2017-12-06 11:14 UTC
# What did you try to do?

Build a endlessloop to request all tokens for a given user to test the databse pool

To reproduce it, you can use a script similar to: 
```sh
#!/bin/bash
readonly PI_AUTH_HEADER="__PUT_AUTH_HEADER_HERE__"
readonly REALM="myrealm"
readonly USER="60d2fad6-be3f-4c50-b849-e948b1b4d4b3"
loop(){
curl "http://localhost:5000/token/?realm=${REALM}&user=${USER}" -H "PI-Authorization: ${PI_AUTH_HEADER}" -H 'Accept: application/json'

loop
}

loop
```

# What outcome did you expect?
The system should answer every request with a httpstatus 200 and all tokens for the given user.

On the user-database side, there should never be more than 10 connections open

# What do you think, how the system should have worked?

There are two ways, the system should have worked. 
The first one, the system allocates all connections for the pool (in my example 10)  and then reuses them.
The second one, it allocates the connection as soon as it is needed (or waits, in case there are count_connections >= pool_size).

# What outcome did you experience?
The system didn't close the connections and recreated a new connection with every request.
To pool and pool size was just ignored.

# What did acutally happen?

(I started the loop multiple times, so this is why try 86 already result in a error) 
```
83 | 09:55:41.612 [info] GET http://privacyidea/token/ -> 200 (117.519 ms)
84 | 09:55:41.750 [info] GET http://privacyidea/token/ -> 200 (137.741 ms)
85 | 09:55:41.878 [info] GET http://privacyidea/token/ -> 200 (127.375 ms)
86 | 09:55:41.924 [error] GET http://privacyidea/token/ -> 500 (45.318 ms)
87 | 09:55:41.966 [error] GET http://privacyidea/token/ -> 500 (41.910 ms)
88 | 09:55:42.013 [error] GET http://privacyidea/token/ -> 500 (46.614 ms)
89 | 09:55:42.060 [error] GET http://privacyidea/token/ -> 500 (47.631 ms)
90 | 09:55:42.108 [error] GET http://privacyidea/token/ -> 500 (47.337 ms)
```
StatusCode 500 =  `OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already`

As you can see, the system just allocates a new connection by every request:
```
[2017-12-06 09:55:41,626][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:41,768][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:41,891][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:41,937][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:41,983][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:42,030][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:42,075][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
[2017-12-06 09:55:42,127][49][139699209266944][DEBUG][privacyidea.lib.resolvers.SQLIdResolver:365] using the connect string postgresql+psycopg2://postgres:postgres@app-db:5432/users
```
The log also tells me `SQLIdResolver:368] using pool_size=10 and pool_timeout=10`. 

So I checked on my app-db_1, if there are any open connections:
```
postgres=# SELECT client_addr, count(*)  FROM pg_stat_activity GROUP BY client_addr ORDER BY client_addr DESC;
 client_addr | count 
-------------+-------
             |     6
 172.18.0.4  |    99
(2 rows)
```
 `172.18.0.4`  is the ip of my privacyidea container

The state of all of those activities is `idle in transaction`, which is another hint to my guess.
For example
```
datid            | 16385
datname          | authentication
pid              | 405
usesysid         | 10
usename          | postgres
application_name | 
client_addr      | 172.18.0.4
client_hostname  | 
client_port      | 39028
backend_start    | 2017-12-06 12:55:42.87198+00
xact_start       | 2017-12-06 12:55:42.891215+00
query_start      | 2017-12-06 12:55:42.926619+00
state_change     | 2017-12-06 12:55:42.926743+00
wait_event_type  | Client
wait_event       | ClientRead
state            | idle in transaction
backend_xid      | 
backend_xmin     | 
query            | SELECT privacyidea_users.id AS privacyidea_users_id, privacyidea_users.username AS privacyidea_users_username, privacyidea_users.user_id AS privacyidea_users_user_id +
                 | FROM privacyidea_users                                                                                                                                                +
                 | WHERE privacyidea_users.username LIKE 'd07fb89d-072e-47de-a717-e663abe5303c'
backend_type     | client backend
```

# Configuration

* privacyIDEA Version: 2.20.1

* Installation method: docker
```
FROM tiangolo/uwsgi-nginx:python2.7

RUN pip install -I privacyIDEA==2.20.1 psycopg2
ENV PRIVACYIDEA_CONFIGFILE /app/pi_config.py
```

This is my resolver. The DB_* Params will be set by Env. :
```
{
  "Driver": "postgresql+psycopg2",
  "Server": DB_HOST,
  "Port": DB_PORT,
  "Database": DB_NAME,
  "User": DB_USER,
  "Password": DB_PASSWORD,
  "Table": "privacyidea_users",
  "Map": '{"userid": "username", "username": "username"}',
  "poolSize": "10",
  "poolTimeout": "10",
  "Limit": "500"
}
```

## more details: 

OS: Debian Jessie (Dockerized)

Webserver: uwsgi

Tokendatabase: postgres:10 (Dockerized)

# Log file
Here's a StackTrace

```
[2017-12-06 09:55:42,012] ERROR in app: Exception on /token/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/site-packages/privacyidea/api/auth.py", line 324, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/api/before_after.py", line 80, in before_user_request
    before_request()
  File "/usr/local/lib/python2.7/site-packages/privacyidea/api/before_after.py", line 113, in before_request
    request.User = get_user_from_param(request.all_data)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 577, in get_user_from_param
    resolver=param.get("resolver"))
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 98, in __init__
    self._get_user_from_userstore()
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/usercache.py", line 63, in cache_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 106, in _get_user_from_userstore
    self._get_resolvers()
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 208, in _get_resolvers
    if self._locate_user_in_resolver(resolvername):
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 223, in _locate_user_in_resolver
    y = get_resolver_object(resolvername)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/resolver.py", line 354, in get_resolver_object
    r_obj.loadConfig(resolver_config)
  File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/resolvers/SQLIdResolver.py", line 388, in loadConfig
    self.TABLE = self.db.entity(self.table)
  File "/usr/local/lib/python2.7/site-packages/sqlsoup.py", line 459, in entity
    return self.map_to(attr, tablename=attr, schema=schema)
  File "/usr/local/lib/python2.7/site-packages/sqlsoup.py", line 342, in map_to
    schema=schema or self.schema)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 514, in _init
    include_columns, _extend_on=_extend_on)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 527, in _autoload
    _extend_on=_extend_on
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2044, in run_callable
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already
```

**Comment by mrmstn** [comment] 2017-12-06 12:45
I've just added pgbouncer (https://pgbouncer.github.io/) in between my db and privacyidea. 
This is what happen, after privacyidea created 10 connections on pgbouncer :

```
pgbouncer_1       | 2017-12-06 12:38:53.704 1 LOG Stats: 0 req/s, in 1050 b/s, out 650 b/s,query 17053 us
pgbouncer_1       | 2017-12-06 12:39:53.705 1 LOG Stats: 0 req/s, in 0 b/s, out 0 b/s,query 0 us
pgbouncer_1       | 2017-12-06 12:40:32.221 1 LOG C-0x55a4bb69cca0: authentication/postgres@172.18.0.7:41746 closing because: query_wait_timeout (age=120)
pgbouncer_1       | 2017-12-06 12:40:32.221 1 WARNING C-0x55a4bb69cca0: authentication/postgres@172.18.0.7:41746 Pooler Error: query_wait_timeout
privacyidea_1     | [2017-12-06 12:40:32,225] ERROR in app: Exception on /token/ [GET]
privacyidea_1     | Traceback (most recent call last):
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
privacyidea_1     |     response = self.full_dispatch_request()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
privacyidea_1     |     rv = self.handle_user_exception(e)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
privacyidea_1     |     reraise(exc_type, exc_value, tb)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
privacyidea_1     |     rv = self.preprocess_request()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
privacyidea_1     |     rv = func()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/api/auth.py", line 324, in decorated_function
privacyidea_1     |     return f(*args, **kwargs)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/api/before_after.py", line 80, in before_user_request
privacyidea_1     |     before_request()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/api/before_after.py", line 113, in before_request
privacyidea_1     |     request.User = get_user_from_param(request.all_data)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
privacyidea_1     |     return func(*args, **kwds)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 577, in get_user_from_param
privacyidea_1     |     resolver=param.get("resolver"))
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
privacyidea_1     |     return func(*args, **kwds)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 98, in __init__
privacyidea_1     |     self._get_user_from_userstore()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/usercache.py", line 63, in cache_wrapper
privacyidea_1     |     return wrapped_function(*args, **kwds)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 106, in _get_user_from_userstore
privacyidea_1     |     self._get_resolvers()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 208, in _get_resolvers
privacyidea_1     |     if self._locate_user_in_resolver(resolvername):
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 223, in _locate_user_in_resolver
privacyidea_1     |     y = get_resolver_object(resolvername)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
privacyidea_1     |     return func(*args, **kwds)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/resolver.py", line 354, in get_resolver_object
privacyidea_1     |     r_obj.loadConfig(resolver_config)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/privacyidea/lib/resolvers/SQLIdResolver.py", line 388, in loadConfig
privacyidea_1     |     self.TABLE = self.db.entity(self.table)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlsoup.py", line 459, in entity
privacyidea_1     |     return self.map_to(attr, tablename=attr, schema=schema)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlsoup.py", line 342, in map_to
privacyidea_1     |     schema=schema or self.schema)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 439, in __new__
privacyidea_1     |     metadata._remove_table(name, schema)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
privacyidea_1     |     compat.reraise(exc_type, exc_value, exc_tb)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 434, in __new__
privacyidea_1     |     table._init(name, metadata, *args, **kw)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 514, in _init
privacyidea_1     |     include_columns, _extend_on=_extend_on)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 527, in _autoload
privacyidea_1     |     _extend_on=_extend_on
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2044, in run_callable
privacyidea_1     |     with self.contextual_connect() as conn:
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
privacyidea_1     |     self._wrap_pool_connect(self.pool.connect, None),
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
privacyidea_1     |     e, dialect, self)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
privacyidea_1     |     exc_info
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
privacyidea_1     |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
privacyidea_1     |     return fn()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
privacyidea_1     |     return _ConnectionFairy._checkout(self)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
privacyidea_1     |     fairy = _ConnectionRecord.checkout(pool)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
privacyidea_1     |     rec = pool._do_get()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
privacyidea_1     |     self._dec_overflow()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
privacyidea_1     |     compat.reraise(exc_type, exc_value, exc_tb)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
privacyidea_1     |     return self._create_connection()
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
privacyidea_1     |     return _ConnectionRecord(self)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
privacyidea_1     |     self.__connect(first_connect_check=True)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 661, in __connect
privacyidea_1     |     exec_once(self.connection, self)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 246, in exec_once
privacyidea_1     |     self(*args, **kw)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
privacyidea_1     |     fn(*args, **kw)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 172, in on_connect
privacyidea_1     |     do_on_connect(conn)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 642, in on_connect
privacyidea_1     |     fn(conn)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 617, in on_connect
privacyidea_1     |     hstore_oids = self._hstore_oids(conn)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 788, in oneshot
privacyidea_1     |     result = fn(self, *args, **kw)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 651, in _hstore_oids
privacyidea_1     |     oids = extras.HstoreAdapter.get_oids(conn)
privacyidea_1     |   File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 904, in get_oids
privacyidea_1     |     """ % typarray)
privacyidea_1     | DatabaseError: (psycopg2.DatabaseError) query_wait_timeout
privacyidea_1     | server closed the connection unexpectedly
privacyidea_1     | 	This probably means the server terminated abnormally
privacyidea_1     | 	before or while processing the request.
```

**Comment by cornelinux** [comment] 2018-02-13 08:55
There are acutally three places where database connections occur.

* The token database itself
* The audit log
* The SQL resolver.

Each of them can be configured in different places.

* The token database would be configured in pi.cfg with the default SQLALCHEMY options.
* The auditlog is configured in pi.cfg with ``PI_AUDIT_POOL_SIZE``.
* The SQL resolver pool size is configured in the resolver configuration.

So actually privacyIDEA can create more than 10 (e.g. at least 3 x 10) connections to the database, since the different modules hold their own pool.

@mrmstn  Maybe this adds some insight?

How did you configure the above mentioned pools?
You might turn of the audit log to check if there is interference from that, to narrow down the problem.

**Comment by fredreichbier** [comment] 2018-08-08 14:33
This is probably related to #1140.

**Comment by plettich** [comment] 2019-09-03 14:52
I can confirm that this works with the `PI_ENGINE_REGISTRY_CLASS = "shared"` entry.
Even without the setting this still works, so i am closing this issue.

**Closed by plettich** 2019-09-03 14:52 UTC
