### ISSUE TITLE
Tags in the text of the email token

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3330] opened 2022-10-11 13:02 UTC
The customization of the e-mail token is not working.

The documentation says that the following tags can be [used](https://privacyidea.readthedocs.io/en/latest/policies/authentication.html#emailtext).
       {otp} or <otp> the One-Time-Password
        {serial} or <serial> the serial number of the token.
        {user} the given name of the token owner.
        {givenname} the given name of the token owner.
        {surname} the surname of the token owner.
        {username} the loginname of the token owner.
        {userrealm} the realm of the token owner.
        {tokentype} the type of the token.
        {recipient_givenname} the given name of the recipient.
        {recipient_surname} the surname of the recipient.
        {time} the current server time in the format HH:MM:SS.
        {date} the current server date in the format YYYY-MM-DD

But only `<otp>` and `<serial>` are working.

I tested all the tags with both forms  {tag} and `<tag>`.
{tag} is generating an error message during the login
        Error message on the WebGui: 
        Authentication failed. Authentication failure. Wrong credentials

        Error message in the logs: 
        [2022-10-11 14:21:10,797][11094][140002954303232][WARNING][privacyidea.lib.tokens.emailtoken:315] The PIN was correct, but the EMail could not be sent! ('tokentype')

`<tag>` is not interpreted and is displayed in the email as `<tag>`

**Comment by plettich** [comment] 2022-10-12 13:25
When we drop Python 2 we can use [`format_map()`](https://docs.python.org/3.8/library/stdtypes.html?highlight=format_map#str.format_map).
Until then we can catch the `KeyError` or check if all given keys exist in the dictionary.

**Comment by cornelinux** [comment] 2022-10-15 06:16
@sepp67 the tags are interpreted. But, as @plettich pointed out, if the tag may not exist, it raises a KeyError.
the curly tags are known to work in /validate/check. I assume that during `/auth` (login to the webui) some information do not exist and thus some values in tags can not be used.
However, this is s.th. we have at several points, that the admin needs to know, what he is configuring and which information is available. (See extended policies --- otherwise it might also contradict his expected outcome).

E.g. if a user logs in without a 2nd factor, there is no tokentype.

So, works as intended. So I am moving this to known issue.

**Comment by cornelinux** [comment] 2023-01-25 14:47
It looks like this line causes all the problems:
https://github.com/privacyidea/privacyidea/blob/754f49b32760097a34af7d8b08b4424e32057080/privacyidea/lib/tokens/emailtoken.py#L386

**Comment by cornelinux** [comment] 2023-01-25 14:50
I add a fix to 3.8.1 and then the following tags will work:

* otp
* serial
* tokenowner
* tokentype
* recipient

**Comment by plettich** [comment] 2023-02-09 15:22
merged into master in 66d4a7b0

**Closed by plettich** 2023-02-09 15:22 UTC
Labels: Type: Bug, Status: Waiting for merge into master
