### ISSUE TITLE
PrivacyIDEA should determine the expiration status of a challenge internally

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/privacyidea#1837] opened 2019-09-03 16:41 UTC
Token-challenges have an expiry associated with them. Currently it is left to the client talking to PI to check, whether a challenge is actually still valid, before allowing the user to sign in.

This leads to several problems:
1. It is easy to forget to check this, see: https://github.com/privacyidea/privacyidea-owncloud-app/issues/73
2. It may not be possible for the client to determine whether the token is still valid, since the client has to guess the timezone of the PI-server, see: #1586 
3. If there is any difference (even just 30 seconds) between the clocks of client and server, this way of checking challenge validity can lead to hard-to-debug errors.

A nicer way to handle this, would be to add a Boolean indicating whether a challenge has expired to /token/challenges

**Comment by fredreichbier** [comment] 2019-09-04 06:27
I agree, I think adding a boolean flag to the ``/token/challenges`` response is a good idea.

**Comment by cornelinux** [comment] 2019-09-06 05:36
Again, the validity of the challenge was always ment for the time, in wich is has to be answered. 
If the challenge was answered succussfully in within the validity period, it is fine.

**Comment by cornelinux** [comment] 2019-09-06 05:53
This is an duplicate of #1838. Whell #1838 is a duplicate of this issue. But since there is more information in #1838, I close this issue. The owncloud App then should use the new endpoint from #1838 or /validate/check with an empty password for push and tiqr.

**Closed by cornelinux** 2019-09-06 05:53 UTC
Labels: Topic: Token, Type: Idea!
