### ISSUE TITLE
4eyes validation get error :maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by yangboyd** [privacyidea/privacyidea#1892] opened 2019-10-16 14:06 UTC
It seems privacyidea falls in a indefinite loop  authenticating the 4eyes token itself.

File "/Users/nobody/nobody/privacyidea/privacyidea/lib/tokens/foureyestoken.py", line 249, in authenticate
    res, reply = check_realm_pass(realm, otp)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 1908, in check_realm_pass
    allow_reset_all_tokens=False)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 93, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 638, in reset_all_user_tokens
    r = wrapped_function(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 2120, in check_token_list
    tokenobject.authenticate(passw, user, options=options)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/decorators.py", line 45, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/tokens/foureyestoken.py", line 249, in authenticate
    res, reply = check_realm_pass(realm, otp)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 1908, in check_realm_pass
    allow_reset_all_tokens=False)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 93, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 638, in reset_all_user_tokens
    r = wrapped_function(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 2120, in check_token_list
    tokenobject.authenticate(passw, user, options=options)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/decorators.py", line 45, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/tokens/foureyestoken.py", line 249, in authenticate
    res, reply = check_realm_pass(realm, otp)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 1908, in check_realm_pass
    allow_reset_all_tokens=False)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 93, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/policydecorators.py", line 638, in reset_all_user_tokens
    r = wrapped_function(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/token.py", line 2120, in check_token_list
    tokenobject.authenticate(passw, user, options=options)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/decorators.py", line 45, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/Users/nobody/nobody/privacyidea/privacyidea/lib/tokens/foureyestoken.py", line 249, in authenticate

**Comment by plettich** [comment] 2019-10-18 13:44
I can confirm this error, i'll look into it.

**Comment by plettich** [comment] 2019-10-22 15:37
This happens if the realm of the token is the same as one of the required tokens. In this case the [`check_realm_pass()`](https://github.com/privacyidea/privacyidea/blob/931e3aeeacbd195d9a7f673e704f2375b558e3a5/privacyidea/lib/token.py#L1880) function finds the 4-eys-token again and dives into the loop.
We should pass an option to exclude certain serials and/or users to `check_realm_pass()`.

**Comment by safiyat** [comment] 2019-12-03 21:45
@plettich When can we expect a fix to this?

Or if you are too busy, maybe you could give a little more information about the solution and I could raise a PR?

**Comment by plettich** [comment] 2019-12-04 09:39
> @plettich When can we expect a fix to this?

This should be fixed in the next release (3.3). We just released 3.2 so this will take a little time.

> Or if you are too busy, maybe you could give a little more information about the solution and I could raise a PR?

A very simple fix would be to use users from different realms for the 4-eyes-token.

**Comment by cornelinux** [comment] 2020-01-25 18:46
@safiyat I am not quite sure what we should fix here. As @plettich pointed out, you shoudl have different realms.
The idea is to have realms where "normal" user or "tokenowners" reside. 
What would you use the 3eyes token for? It is ment for a very specific user - probably in a very specific realm. This way you wount stumble into any *logical* problem.
Again: If you can give some pointers, what you actually would expect, we can better evaluate if, what, how we do what.

**Comment by safiyat** [comment] 2020-01-26 04:31
@cornelinux The requirement is that we want to have 4eyes enabled for the engineers in the DevOps team. The engineers in this context (of 4eyes) are all hierarchically at the same level, and hence we can't have some designated as the superiors. Hence, the requirement that tokens of the same realm can be used for 4eyes, with the caveat that they should not be of the same user.

Currently we are using the tokens from different realms as a workaround for the issue. So, all the engineers have a token each in two realms A & B. One engineer uses the token from realm A and the other uses his/her token from realm B for authentication.

If this is a very specific requirement, we are fine with it not getting fixed.

**Comment by cornelinux** [comment] 2020-01-26 07:18
Thanks for your response @safiyat. This is an interesting scenario although it is not the intended use case for the 4eyes token. If I understand it correctly you are giving each engineer one OTP token and one 4eyes token (preferably in the same realm). Then you want the engineer who is logging in (with his OTP token) to wait for a 2nd engineer to "confirm" the login with the OTP token of the 2nd engineer.

So you have EngineerA, EngineerB and EnigneerC. And EngineerA can only login when EngineerA presents his token and either EnigeerB or EngineerC.

But, the design of the 4eyes token is based on a different concept:
It is ment this way: The "role" SuperuserA can only login if two of EngineerA, EngineerB and EngineerC come an impersonate as SuperuserA.

So even if we fix the issue, that 4eyes tokens should be excluded tokens being available for impersonation for 4eyes tokens you will have this effect: *warning*

EngineerA and EngineerB can come togeather and impersonate as EngineerC. This is why we implicitly assumed that the users who get impersonated are users who are impersonating are disjoint sets. You need to be aware of this and rethink if this is actually what you want!?

However...

# How to fix this

The problem arises here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/foureyestoken.py#L263
We need to exclude 4eyes tokens from being checked in ``check_realm_pass``.
Although it looks like ``check_realm_pass`` is only used in the 4eyes token I would add a parameter (possibly in the ``options``) that contains the allowed (or not allowed) token types to be searched.

Tokens are fetched from the realm here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L1907
Since ``get_tokens`` only takes *one* token type, we would have to iterate over the tokentypes.

**Closed** 2020-08-04 15:46 UTC
Labels: Topic: Token, Type: Known issue
