### ISSUE TITLE
Add possibility to change page title

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1624] opened 2019-05-13 12:58 UTC
#1621 documents how the Apache substitute module can be used to change the page title from "privacyIDEA Authenticaiton System" to something else. It would be nice if we would provide a built-in way to change the page title.

We could, e.g., store the page title in a config variable, or provide a default template that can be overridden.

**Comment by cornelinux** [comment] 2019-05-13 19:50
Aha, this is a duplicate of #1243

**Closed by cornelinux** 2019-05-13 19:50 UTC
Labels: enhancement
